### ISSUE TITLE
Equality constraints?

### ISSUE THREAD

**Issue by ddssff** [nikita-volkov/th-instance-reification#1]
Could you discuss why typesSatisfyDecConstraints doesn't analyze equality constraints?  Is it difficult, or is it unnecessary for your application, or something else?

**Comment by nikita-volkov** [comment]
Frankly, I don't remember ) I think it was a limitation of functions of  the "template-haskell" library, which I utilize in this solution, but I'm not sure. The source is quite trivial and well documented, so you can check it out for yourself.

**Comment by ddssff** [comment]
I ask because I implemented the same thing but I'm being told my unification algorithm for handling EqualP predicates is incorrect: https://github.com/seereason/th-desugar/blob/master/Language/Haskell/TH/Desugar/Context.hs

**Comment by nikita-volkov** [comment]
Unfortunately I don't have the time to dive into this subject right now, so I wish you the best in figuring this one out.

**Comment by ddssff** [comment]
I am closing this because I have an adequate solution in my th-desugar branch now.
